### ISSUE TITLE
Plugin blocks response of permission_handler plugin

### ISSUE THREAD

**Issue by boskokg** [kevincaicedo/imei_plugin#9]
Hello,
I tried your plugin, but somehow your plugin blocks result of permission_handler (and maybe some other plugin).
I reproduced this issue on Android.
To reproduce the issue:

- download permission_handler
- include your plugin in pub.xml
- start android example of permission_handler
- invoke permission request and notice that code after the return is never performed...

Note:device_id: 0.2.0 works just fine with plugin permission_handler

**Comment by kevincaicedo** [comment]
Hi boskokg.
This is fix in version 1.1.4

https://pub.dev/packages/imei_plugin/versions/1.1.4

**Comment by boskokg** [comment]
Thanks, but as I already wrote, I switched to device_id plugin. I don't see a reason why I should start using your plugin since device_id works fine.
I also don't see a reason you still maintenance your plugin since there is already the same one.
